[package]
name = "flag"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
rand = "0.8.5"
unic = "0.9.0"
unic-normal = "0.9.0"
unic-ucd-category = "0.9.0"
unic-ucd-normal = "0.9.0"
