services:
  web:
    container_name: "nginxAuth103"
    image: nginx:1.25
    volumes:
      - ./html:/usr/share/nginx/html:ro
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9002:80"
  express:
    container_name: "expressAuth103"
    build: ./express
    volumes:
      - ./express:/usr/src/app
    ports:
      - ":10000"