FROM node

# Create app directory
WORKDIR /usr/src/app

# Copy package.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all files
COPY *.js .
COPY .env .env

# Expose port 3000
EXPOSE 4000

# Run app
CMD [ "node", "index.js" ]
